### ISSUE TITLE
Increase peers limits of seed nodes

### ISSUE THREAD

**Issue by dincho** [aeternity/terraform-aws-mainnet#19]
Suggestion:

```
sync:
    max_inbound: 200
    max_outbound: 30
```

**Comment by ThomasArts** [comment]
Worst case, the node would talk to 230 peers at the same time. Do we have any maths on whether receiving the same micro block 230 times would be an issue?

Probably start increasing on a few nodes and keep an eye on them while others a re a bit more limited

**Comment by sennui** [comment]
This is setting only until we fix sync peer list handling. Talking here about worst case need to include probability of it, which is low as we have large number of dead peers.

**Comment by jur0** [comment]
I wouldn't increase `max_inbound` to 200. I'd keep it as it was (100) or even decrease it.
